spring:
  application:
    name: myrealstore-server

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/myrealstore
    username: test
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


payment:
  toss:
    base-url: https://api.tosspayments.com/v1
    client-key: test_ck_KNbdOvk5rk5RxdPn4W2y3n07xlzm
    secret-key: test_sk_4yKeq5bgrpLMAgv90blJrGX0lzW6
